FROM nginx:latest

# Remove the default Nginx welcome page
RUN rm -f /usr/share/nginx/html/index.html

# Copy your custom "index.html" file to the web server's document root
COPY index.html /usr/share/nginx/html/

