stages:
  - init
  - validate
  - plan
  - apply

variables:
  TF_WORKING_DIR: "emea-terraform-aws/Terra-ec2-docker"
  TF_PLAN_FILE: "myplan"
  TERRAFORM_VERSION: "1.1.0"
  AWS_ACCESS_KEY_ID: "ASIAXFBC2EFTS4MZTEDP"  # Update with your AWS access key
  AWS_SECRET_ACCESS_KEY: "ehMTL6AjpCbb7ClI/s/BLLkuh3sfAcKv8okmdnAw"  # Update with your AWS secret key

before_script:
  - apt-get update -qy
  - apt-get install -y unzip
  - wget https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - rm -rf terraform_${TERRAFORM_VERSION}_linux_amd64.zip

init:
  stage: init
  script:
    - cd $TF_WORKING_DIR
    - terraform init

validate:
  stage: validate
  script:
    - cd $TF_WORKING_DIR
    - terraform validate

plan:
  stage: plan
  script:
    - cd $TF_WORKING_DIR
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - terraform init
    - terraform plan -out=$TF_PLAN_FILE

apply:
  stage: apply
  script:
    - cd $TF_WORKING_DIR
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - terraform init
    - terraform apply -auto-approve $TF_PLAN_FILE
